{"name": "Ошибка при несуществующем трек-номере", "status": "passed", "steps": [{"name": "Получить заказ по треку №999999", "status": "passed", "parameters": [{"name": "track", "value": "999999"}], "start": 1745092822358, "stop": 1745092822436}], "start": 1745092822358, "stop": 1745092822437, "uuid": "8ea0497c-e4cf-4862-ba36-f58d62d06f9f", "historyId": "9b21e8a9692d522164151bd8ffea41b8", "testCaseId": "9b21e8a9692d522164151bd8ffea41b8", "fullName": "tests.test_order.TestOrderByTrack#test_get_order_invalid_track", "labels": [{"name": "feature", "value": "Получение заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderByTrack"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "19536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}