{"name": "Ошибка при неверном ID заказа", "status": "passed", "statusDetails": {"message": "XPASS API возвращает 500 вместо 404"}, "steps": [{"name": "Принять заказ №999999 курьером 506622", "status": "passed", "parameters": [{"name": "order_id", "value": "999999"}, {"name": "courier_id", "value": "506622"}], "start": 1745144617701, "stop": 1745144617732}], "attachments": [{"name": "log", "source": "c8fea97d-8284-45f0-a88b-12ced1aa248f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5483bc04-b882-4b26-a90f-9f39762346fe-attachment.txt", "type": "text/plain"}], "start": 1745144617700, "stop": 1745144617732, "uuid": "7283a768-a222-4d94-9dac-9658018a992b", "historyId": "0045170f006f8e281a3b96222e577171", "testCaseId": "0045170f006f8e281a3b96222e577171", "fullName": "tests.test_order.TestOrderAcceptance#test_accept_order_invalid_order_id", "labels": [{"name": "feature", "value": "Принятие заказов"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='API возвращает 500 вместо 404')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderAcceptance"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "17288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}