{"name": "Ошибка при неверном ID заказа", "status": "passed", "statusDetails": {"message": "XPASS API возвращает 500 вместо 404"}, "steps": [{"name": "Принять заказ №999999 курьером 506057", "status": "passed", "parameters": [{"name": "order_id", "value": "999999"}, {"name": "courier_id", "value": "506057"}], "start": 1745092822049, "stop": 1745092822063}], "attachments": [{"name": "log", "source": "232eab06-c4fb-469d-b2b0-865e9669b159-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "317090ec-72c7-445b-bcc5-7d4f3acf812d-attachment.txt", "type": "text/plain"}], "start": 1745092822049, "stop": 1745092822063, "uuid": "c15ab260-7b9f-41e4-9a66-19d29b5c25e3", "historyId": "0045170f006f8e281a3b96222e577171", "testCaseId": "0045170f006f8e281a3b96222e577171", "fullName": "tests.test_order.TestOrderAcceptance#test_accept_order_invalid_order_id", "labels": [{"name": "feature", "value": "Принятие заказов"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='API возвращает 500 вместо 404')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderAcceptance"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "19536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}