{"name": "Ошибка при несуществующем трек-номере", "status": "passed", "steps": [{"name": "Получить заказ по треку №999999", "status": "passed", "parameters": [{"name": "track", "value": "999999"}], "start": 1745261087109, "stop": 1745261087183}], "start": 1745261087108, "stop": 1745261087184, "uuid": "52d6376f-e2ec-4d2b-9e86-b9363c138863", "historyId": "9b21e8a9692d522164151bd8ffea41b8", "testCaseId": "9b21e8a9692d522164151bd8ffea41b8", "fullName": "tests.test_order.TestOrderByTrack#test_get_order_invalid_track", "labels": [{"name": "feature", "value": "Получение заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderByTrack"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "2332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}