{"name": "Ошибка при неверном ID курьера", "status": "passed", "statusDetails": {"message": "XPASS API возвращает 500 вместо 404"}, "steps": [{"name": "Принять заказ №455131 курьером 'invalid_courier_id'", "status": "passed", "parameters": [{"name": "order_id", "value": "455131"}, {"name": "courier_id", "value": "'invalid_courier_id'"}], "start": 1745261085926, "stop": 1745261085952}], "attachments": [{"name": "log", "source": "e03c6c04-bb7b-435d-9e51-54ff5a8e1f5f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "30921087-cf98-4143-9dc4-46c878f968b3-attachment.txt", "type": "text/plain"}], "start": 1745261085926, "stop": 1745261085953, "uuid": "dddc902b-f227-4a92-84e5-d1420c11da86", "historyId": "32c9abb9e238f9170f6964d25ca2b702", "testCaseId": "32c9abb9e238f9170f6964d25ca2b702", "fullName": "tests.test_order.TestOrderAcceptance#test_accept_order_invalid_courier_id", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='API возвращает 500 вместо 404')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderAcceptance"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "2332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}